version: '3.9'

services:
  backend:
    build:
      context: .
      target: ${BUILD_TARGET-runtime}
    environment:
      RUNTIME_ENV: ${RUNTIME_ENV:-live}
      APP_DATA_DIR: ${APP_DATA_DIR:-/mnt/data}
      APP_SERVER_PORT: ${APP_SERVER_PORT:-8080}
    ports:
      - 8080:8080
    networks:
      - reverse_proxy
    restart: unless-stopped
    volumes:
      - data:/mnt/data

networks:
  reverse_proxy:
    driver: bridge
    external: true
    name: reverse_proxy

volumes:
  data:
